language: node_js
node_js: 
  - node
dist: bionic

notifications:
  email:
    recipients:
      - gionnieve@gmail.com
    on_success: always
    on_failure: always
    
sudo: required

branches:
  only:
   - master

before_script:
  - npm install -g @angular/cli
  - npm audit fix
  
script:
  - ng lint
  - ng build --prod --base-href https://gionnievencs.github.io/bitcoin-order-app/

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/bitcoin
  on: 
   branch: master
